name: flutter_parallax_scroll_example
description: Example app for flutter_parallax_scroll package
publish_to: 'none'

version: 0.0.3+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_parallax_scroll:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 